repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
    - id: seed-isort-config

  - repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: poetry run flake8 --max-line-length 120 --exclude ^(tests|Examples|Docs)
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]

  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: master
    hooks:
    - id: prettier
      name: prettier qml plugin
      additional_dependencies:
      - prettier@1.19.1
      - "prettier-plugin-qml@0.10.2"
      files: \.qml$
      exclude: /tests

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v2.2.2
    hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
