name: Code Style Checker

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: Gr1N/setup-poetry@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Verify Commit
        run: |
          poetry update
          poetry run pre-commit run --all-files
        env:
          SKIP: prettier
